config/routes.rb
Rails.application.routes.draw do 

resources :comments

 resources :articles do
  collection { post :import}
 end

 root to: 'articles#index'

end

app/models/article.rb
class Article < ActiveRecord::Base
validates :title, presence: true,
length: { minimum: 5 }
validates :content, presence: true,
length: { minimum: 10 }
validates :status, presence: true
default_scope {where(status: 'active')}

has_many :comments
validates_presence_of :content, :title, :status

 def self.to_csv(options = {})
 	CSV.generate(options) do |csv|
 		csv << column_names
 		all.each do |article|
 			csv << article.attributes.values_at(*column_names)
 		end
 	end
 end

 def self.import(file)
 	CSV.foreach(file.path, headers: true) do |row|
 		Article.create! row.to_hash
 	end
 end

 def self.search(query)
  # where(:title, query) -> This would return an exact match of the query
    where("title like ?", "%#{query}%") 
end
end

app/models/comment.rb
class Comment < ActiveRecord::Base
belongs_to :article
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def index
   if params[:search]
       @articles = Article.search(params[:search]).paginate :page => params[:page], :per_page => 7
    else
      @articles = Article.paginate :page => params[:page], :per_page => 7
    end
    UserMailer.send_signup_email().deliver
   #@articles = Article.paginate :page => params[:page], :per_page => 8
   respond_to do |format|
      format.xls  { send_data @articles.to_csv(col_sep: "\t")}
      format.html
      format.csv  { send_data @articles.to_csv}
    end
  end

  def new
   @article = Article.new
  end

  def edit
   @article = Article.find_by_id(params[:id])
  end
  
  def show
   @article = Article.find_by_id(params[:id])
   @comments = @article.comments
   @comment = Comment.new
    
  end
  
  def create
   @article = Article.new(params_article)
   if @article.save
    flash[:notice] = "Success Add Records"
    redirect_to action: 'index'
   else
    flash[:error] = "data not valid"
    render 'new'
   end
  end
  
  def update
   @article = Article.find_by_id(params[:id])
   if @article.update(params_article)
    flash[:notice] = "Success Update Records"
    redirect_to action: 'index'
   else
    flash[:error] = "data not valid"
    render 'edit'
   end
  end
  
  def destroy
   @article = Article.find_by_id(params[:id])
   if @article.destroy
    flash[:notice] = "Success Delete a Records"
    redirect_to action: 'index'
   else
    flash[:error] = "fails delete a records"
    redirect_to action: 'index'
   end
  end
  
  def import
   Article.import(params[:file])
   redirect_to action: 'index', notice: "Articles imported!"
  end


  private
   def params_article
    params.require(:article).permit(:title, :content, :status)
   end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def index
   @comments = Comment.all
  end

  def new
  @comment = Comment.new
  end

  def edit
  end
  
  def create
   @comment = Comment.new(comment_params)
   if @comment.save
     flash[:success] = 'Your comment was successfully added!'
     redirect_to article_url(params[:comment][:article_id])
   else
     render 'new'
   end
  end
 
 private
 
  def comment_params
    params.require(:comment).permit(:article_id, :content, :username)
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/articles/edit.html.erb
<%= form_for @article do |f| %>
<%= f.label :title %>
&nbsp&nbsp&nbsp&nbsp&nbsp
<%= f.text_field :title, :autofocus=>true%>
<br/>
<br/>
<br/>
<%= f.label :content %>
<%= f.text_area :content, cols: 40, rows: 10 %>
<br/>
<br/>
<br/>
<%= f.label :status %>
&nbsp&nbsp&nbsp
<%= f.radio_button :status, "active" %>
<%= label :article_status, 'active' %>
&nbsp&nbsp&nbsp
<%= f.radio_button :status, "off" %>
<%= label :article_status, 'off' %>
<br/>
<br/>
<%= f.submit :submit %>
<% end %>
<div>
<%= link_to "back to Home", articles_path %>
</div>

app/views/articles/index.html.erb
<p>
  Download Articles:
  <%= link_to "CSV", articles_path(format: "csv") %> |
  <%= link_to "Excel", articles_path(format: "xls") %>
</p>
<% @articles.each do |article| %>
<h3><%= article.title %></h3>
<p>
<%= article.content.truncate(20) %>
<%= link_to 'read more', article_path(article.id) %>
</p>
<h4>status : <%= article.status %></h4>
<p>
<span><%= link_to 'edit', edit_article_path(article.id) %><span>
<span> | </span>
<span><%= link_to 'delete', article_path(article.id), method: "DELETE", data:{confirm: 'Delete this data ? '} %><span>
</p>
<hr/>
<% end %>
<%= will_paginate @articles %>

app/views/articles/index.xls.erb
<table border="1">
<tr>
	<th>Title</th>
	<th>Content</th>
	<th>Status</th>
</tr>
<% @articles.each do |article| %>

<tr>
	<td><%= article.title %></td>
	<td><%= article.content %></td>
	<td><%= article.status %></td>
</tr>
<% end %>
</table>

app/views/articles/new.html.erb
<%= form_for @article do |f| %>
<%= f.label :title %>
&nbsp&nbsp&nbsp&nbsp&nbsp
<%= f.text_field :title, :autofocus=>true %>
<%= @article.errors[:title].first unless @article.errors[:title].blank? %>
<br/>
<br/>
<br/>
<%= f.label :content %>
<%= f.text_area :content, cols: 40, rows: 10 %>
<%=   @article.errors[:content].first   unless   @article.errors[:content].blank? %>
<br/>
<br/>
<br/>
<%= f.label :status %>
&nbsp&nbsp&nbsp
<%= f.radio_button :status, "active", :checked => true %>
<%= label :article_status, 'active' %>
&nbsp&nbsp&nbsp
<%= f.radio_button :status, "off" %>
<%= label :article_status, 'off' %>
<br/>
<br/>
<%= f.submit :POST %>
<% end %>

<br/>
<h3>Import CSV file to add new articles! </h3>
<%= form_tag import_articles_path, multipart: true do %>
	<%= file_field_tag :file %>
	<br/>
	<%= submit_tag "Import", class: 'btn btn-success' %>
<% end %>

app/views/articles/show.html.erb
<h3><%= @article.title %></h3>
<p><%= @article.content %></p>
<br>
<br>
<hr>
<% if @comments %>
  <h3>Comments</h3>
  <% @comments.each do |comment| %>
    <p id="komentar"><%=h comment.username%> : <%=h comment.content %></p>
  <% end %>
<% end %>
<br>
<br>
<hr>

<h3>Post Your Comment</h3>
<%= form_for(@comment) do |f| %>
  <% if @comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:</h2>
 
      <ul>
        <% @comment.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
 
   <div class="form-group">
    <%= f.label :article_id %>
    <%= f.text_field :article_id, :value => @article.id,class: 'form-control', required: true %>
  </div>
  
  <div class="form-group">
    <%= f.label :username %>
    <%= f.text_field :username, class: 'form-control', required: true %>
  </div>
 
  <div class="form-group">
    <%= f.label :content %>
    <%= f.text_area :content, class: 'form-control', required: true %>
  </div>
 
  <%= f.submit  "Post Comment", class: 'btn btn-primary' %>
  <br>
<% end %>

<p><%= link_to 'back to Home', articles_path %></p>

app/views/comments/_comment.html.erb
<div class="well">
  <h2><%= comment.id %></h2>
  <p class="text-muted">Added by <strong><%= comment.user_id %></strong> on
    <%= l(comment.created_at, format: '%B, %d %Y %H:%M:%S') %></p>
 
  <blockquote>
    <p><%= comment.content %></p>
  </blockquote>
</div>

app/views/comments/_form.html.erb
<%= form_for(@comment) do |f| %>
  <% if @comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:</h2>
 
      <ul>
        <% @comment.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
 
 
  <div class="form-group">
    <%= f.label :user_id %>
    <%= f.text_field :user_id, class: 'form-control', required: true %>
  </div>
 
  <div class="form-group">
    <%= f.label :content %>
    <%= f.text_area :content, class: 'form-control', required: true %>
  </div>
 
  <%= f.submit class: 'btn btn-primary' %>
<% end %>

app/views/comments/edit.html.erb
<h1>Comments#edit</h1>
<p>Find me in app/views/comments/edit.html.erb</p>

app/views/comments/index.html.erb
<div class="jumbotron">
  <div class="container">
    <h1>Join the discussion</h1>
    <p>Click the button below to start a new thread:</p>
    <p>
      <%= link_to 'Add new topic', new_comment_path, class: 'btn btn-primary btn-lg' %>
    </p>
  </div>
</div>
 
<%= render @comments %>

app/views/comments/new.html.erb
<h1>New comment</h1>
<%= render 'form' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <title>LIPTIA'S BLOG</title>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= stylesheet_link_tag 'bootstrap', 'bootstrap.min' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'bootstrap', 'bootstrap.min' , 'jquery-1.10.2.min' %>
  <%= csrf_meta_tags %>
</head>
<body>
<nav class="navbar navbar-default">
  <div class="container-fluid">
		<!-- Brand and toggle get grouped for better mobile display -->
		<div class="navbar-header">
		  <a class="navbar-brand" href="<%= articles_path %>">LIPTIA'S BLOG</a>
		</div>

		<!-- Collect the nav links, forms, and other content for toggling -->
		<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
		  <ul class="nav navbar-nav">
			<li><%= link_to "Write New Article" , new_article_path %></li>
		  </ul>
    		<%= form_tag(articles_path, :method => "get", class: "navbar-form", id: "search-form") do %>
         <div class="input-append pull-right" style="margin-bottom:10px;">
          <%= text_field_tag :search, params[:search], class: "form-control", placeholder: "Search Articles" %>
          <input class="btn btn-success" type="submit" value="Search"></input>
         </div>
       <% end %>
		</div><!-- /.navbar-collapse -->
	  </div><!-- /.container-fluid -->
</nav>

<div class="container konten">
<%= yield %>
</div>

    <div class="footer-bottom navbar-fixed-bottom">
        <div class="container">
            <p class="text-center"> Copyright © Liptia's Blog 2015. All right reserved. </p>
            <div class="pull-right">
                <ul class="nav nav-pills payments">
                	<li><i class="fa fa-cc-visa"></i></li>
                    <li><i class="fa fa-cc-mastercard"></i></li>
                    <li><i class="fa fa-cc-amex"></i></li>
                    <li><i class="fa fa-cc-paypal"></i></li>
                </ul> 
            </div>
        </div>
    </div>

</body>
</html>